-- Eventos históricos reales del lote sur (fuentes: prensa colombiana, ReliefWeb/OCHA).
-- Sipí y Río Iró: sin eventos documentados encontrados específicamente para esos
-- municipios en las fuentes consultadas — no se inventaron eventos para ellos.
INSERT INTO eventos_historicos (municipio_id, tipo_evento, fecha, severidad, fuente, descripcion) VALUES
((SELECT id FROM municipios WHERE nombre = 'Medio San Juan'), 'inundacion', '2019-02-23', 'alto', 'El País (Cali)', 'Desbordamiento del río San Juan en la madrugada del sábado 23 de febrero de 2019 inundó varios barrios de Istmina, Andagoya (cabecera de Medio San Juan) y Condoto; el nivel del agua alcanzó varios metros y los residentes no alcanzaron a evacuar sus pertenencias. Fuente: https://www.elpais.com.co/colombia/emergencia-en-varios-municipios-del-choco-por-desbordamiento-del-rio-san-juan.html'),
((SELECT id FROM municipios WHERE nombre = 'Medio San Juan'), 'inundacion', '2024-11-09', 'alto', 'Infobae Colombia', 'Emergencia regional: tras 72 horas continuas de lluvia, el 85% del departamento del Chocó resultó afectado (25 municipios), con Medio San Juan nombrado explícitamente entre los municipios con inundación por desbordamiento de ríos, junto a Istmina, Lloró, Medio y Bajo Baudó. Más de 15.000 personas afectadas y 2 muertos por la creciente del río San Juan. Fuente: https://www.infobae.com/colombia/2024/11/09/el-85-del-departamento-del-choco-esta-en-emergencia-por-las-fuertes-lluvias-asi-lo-informo-la-gobernadora/'),
((SELECT id FROM municipios WHERE nombre = 'Cantón de San Pablo'), 'inundacion', '2019-02-23', 'medio', 'Revista Semana', 'El mismo desbordamiento del río San Juan del 23 de febrero de 2019 provocó inundaciones en Managrú, cabecera de Cantón de San Pablo, además de Istmina y Condoto, según galería fotográfica de Semana. Fuente: https://www.semana.com/nacion/galeria/en-choco-el-rio-san-juan-se-desbordo-y-provoco-inundaciones-en-istmina-condoto-y-managru/602689/'),
((SELECT id FROM municipios WHERE nombre = 'El Litoral del San Juan'), 'inundacion', '2020-05-28', 'medio', 'Radio Nacional de Colombia', 'Fuertes lluvias en el sur del Chocó desbordaron el sistema del río Pichimá, desplazando a 560 personas de la comunidad indígena de Pichimá Quebrada y afectando también a Santa María de Pangalá, sobre el río San Juan (jurisdicción de El Litoral del San Juan); se reportaron pérdidas de cultivos de pancoger y animales de corral. Fuente: https://www.radionacional.co/actualidad/medio-ambiente/inundaciones-afectan-560-personas-de-litoral-del-san-juan-choco'),
((SELECT id FROM municipios WHERE nombre = 'El Litoral del San Juan'), 'inundacion', '2024-11-07', 'alto', 'Infobae Colombia', 'El municipio declaró calamidad pública el 7 de noviembre de 2024 al verse afectadas más de 40 de sus 60 comunidades por el desbordamiento del río San Juan durante la ola invernal que afectó al 85% del Chocó. Fuente: https://www.infobae.com/colombia/2024/11/09/el-85-del-departamento-del-choco-esta-en-emergencia-por-las-fuertes-lluvias-asi-lo-informo-la-gobernadora/'),
((SELECT id FROM municipios WHERE nombre = 'El Litoral del San Juan'), 'inundacion', '2026-08-16', 'critico', 'Vanguardia', 'Una semana después del sismo de magnitud 7,4 del 10 de agosto de 2026 (epicentro en San José del Palmar), fuertes lluvias en la madrugada del domingo 16 de agosto de 2026 provocaron inundaciones y deslizamientos adicionales; la gobernadora declaró El Litoral del San Juan uno de los tres municipios en doble emergencia (sismo + lluvias). Fuente: https://www.vanguardia.com/colombia/2026/08/18/doble-emergencia-en-el-choco-entre-la-destruccion-por-el-terremoto-y-las-fuertes-lluvias/'),
((SELECT id FROM municipios WHERE nombre = 'Nóvita'), 'inundacion', '2020-12-10', 'medio', 'ReliefWeb / Equipo Local de Coordinación', 'Creciente súbita del río Tamaná (09-12 de diciembre de 2020) inundó las comunidades de Brazo de Agua Sucia, Pindaza, Quebrada Larga y Agua Clara en jurisdicción de Nóvita, afectando según el reporte a 146 familias / 438 personas y sus viviendas. Fuente: https://reliefweb.int/report/colombia/colombia-informe-flash-mira-inundaciones-por-la-creciente-s-bita-del-r-o-taman'),
((SELECT id FROM municipios WHERE nombre = 'Nóvita'), 'inundacion', '2021-10-19', 'medio', 'Radio Nacional de Colombia', 'Nuevo desbordamiento del río Tamaná (reportado el 19 de octubre de 2021) dejó al menos 1.000 familias afectadas en la cuenca media y baja del río, con destrucción de cultivos de pancoger de los que depende la seguridad alimentaria de cerca de 5.800 habitantes. Fuente: https://www.radionacional.co/noticias-colombia/desbordamiento-del-rio-tamana-novita-choco'),
((SELECT id FROM municipios WHERE nombre = 'San José del Palmar'), 'deslizamiento', '2026-08-10', 'critico', 'El Tiempo', 'El sismo de magnitud 7,4 del 10 de agosto de 2026 tuvo epicentro en San José del Palmar y generó más de 24 puntos de derrumbe sobre la única vía de acceso al municipio, además de viviendas colapsadas y agrietadas; 441 familias afectadas. El evento detonante fue sísmico, pero los deslizamientos de tierra fueron el efecto documentado sobre la vía y las viviendas. Fuente: https://www.eltiempo.com/colombia/otras-ciudades/grietas-y-mas-de-24-derrumbes-dificultan-el-acceso-a-san-jose-del-palmar-choco-tras-el-terremoto-de-magnitud-7-4-en-colombia-3578067'),
((SELECT id FROM municipios WHERE nombre = 'Alto Baudó'), 'inundacion', '2024-03-16', 'alto', 'Infobae Colombia', 'Lluvias intensas provocaron en marzo de 2024 el desbordamiento del río Baudó y 10 de sus afluentes, generando una crisis humanitaria sin precedentes en Alto Baudó: cerca de 5.000 familias afectadas en 155 comunidades de 43 corregimientos, pérdida de cultivos, y suspensión de agua potable y energía. Fuente: https://www.infobae.com/colombia/2024/03/16/emergencia-en-choco-desbordamiento-del-rio-baudo-dejo-miles-de-familias-damnificadas/');
