-- Eventos históricos reales del lote centro/Atrato (fuentes: prensa colombiana,
-- IDEAM, Wikipedia con referencias cruzadas). Nota: el agente de investigación
-- también encontró un posible evento en Unión Panamericana, pero la propia
-- fuente aclaraba que la afectación directa a ese municipio (más allá de servir
-- de albergue a desplazados de otras zonas) no estaba documentada de forma
-- independiente — se excluyó deliberadamente para no dejar un registro
-- engañoso.
INSERT INTO eventos_historicos (municipio_id, tipo_evento, fecha, severidad, fuente, descripcion) VALUES
((SELECT id FROM municipios WHERE nombre = 'Lloró'), 'inundacion', '2025-10-28', 'alto', 'Infobae', 'Desbordamiento del río Atrato durante la segunda temporada de lluvias de 2025; más de 1.200 familias damnificadas en Lloró y Bagadó, con viviendas y cultivos arrasados por las crecientes del Atrato y el Andágueda. Fuente: https://www.infobae.com/colombia/2025/10/28/emergencia-por-lluvias-en-choco-mas-de-1200-familias-damnificadas-y-15-municipios-afectados/'),
((SELECT id FROM municipios WHERE nombre = 'El Carmen de Atrato'), 'deslizamiento', '2024-01-12', 'critico', 'Wikipedia / Meteored', 'Deslizamiento de tierra masivo en el sector Las Toldas, km 17 de la vía Quibdó-Medellín, tras fuertes lluvias; al menos 37 personas fallecidas (otras fuentes hasta 40) y al menos 35 heridos, viviendas y vehículos sepultados. Fuentes: https://en.wikipedia.org/wiki/2024_El_Carmen_de_Atrato_landslide y https://www.meteored.mx/noticias/actualidad/mortifero-deslizamiento-de-tierra-en-el-carmen-de-atrato-colombia-desastres-cambio-climatico-tipo-y-uso-del-suelo.html'),
((SELECT id FROM municipios WHERE nombre = 'Atrato'), 'inundacion', '2025-08-02', 'medio', 'IDEAM - Boletín de Alertas Hidrológicas No. 221', 'Inundación registrada cerca de la quebrada La Josefa, en el corregimiento de Yuto (municipio de Atrato), documentada en el boletín oficial de alertas hidrológicas de IDEAM para la cuenca del río Quito/Atrato. Fuente: https://www.ideam.gov.co/sites/default/files/prensa/boletines/2025-08-09/221_bah_agosto_09_2025_2200.pdf'),
((SELECT id FROM municipios WHERE nombre = 'Atrato'), 'inundacion', '2025-10-28', 'alto', 'Infobae', 'El municipio de Atrato figura entre las zonas donde el desbordamiento del río Atrato destruyó viviendas y cultivos durante la emergencia invernal de finales de octubre de 2025 que dejó más de 1.200 familias damnificadas en el departamento. Fuente: https://www.infobae.com/colombia/2025/10/28/emergencia-por-lluvias-en-choco-mas-de-1200-familias-damnificadas-y-15-municipios-afectados/'),
((SELECT id FROM municipios WHERE nombre = 'Medio Atrato'), 'inundacion', '2025-10-28', 'alto', 'Infobae', 'Medio Atrato figura junto con Atrato y Bagadó entre los municipios donde el desbordamiento del río Atrato destruyó viviendas y cultivos en la emergencia invernal de finales de octubre de 2025. Fuente: https://www.infobae.com/colombia/2025/10/28/emergencia-por-lluvias-en-choco-mas-de-1200-familias-damnificadas-y-15-municipios-afectados/'),
((SELECT id FROM municipios WHERE nombre = 'Bagadó'), 'inundacion', '2025-10-28', 'alto', 'Infobae / La FM', 'Familias atrapadas por el agua tras el desbordamiento del río Atrato y el río Andágueda; más de 1.200 familias damnificadas en Lloró y Bagadó, viviendas ribereñas inundadas y cultivos destruidos. Fuentes: https://www.infobae.com/colombia/2025/10/28/emergencia-por-lluvias-en-choco-mas-de-1200-familias-damnificadas-y-15-municipios-afectados/ y https://www.lafm.com.co/actualidad/familias-atrapadas-por-el-agua-en-lloro-y-bagado-tras-el-desbordamiento-del-rio-atrato-en-choco-380963'),
((SELECT id FROM municipios WHERE nombre = 'Cértegui'), 'inundacion', '2019-02-23', 'alto', 'El País (Colombia) / OCHA Colombia', 'Desbordamiento de los ríos San Juan, Iró, Condoto, Cértegui y Quito tras fuertes lluvias; inundaciones súbitas y progresivas afectaron a Condoto, Tadó, Cértegui, Medio San Juan, Río Iró e Istmina, con más de 15.450 personas y 3.200 familias afectadas según OCHA. Fuente: https://www.elpais.com.co/colombia/emergencia-en-varios-municipios-del-choco-por-desbordamiento-del-rio-san-juan.html'),
((SELECT id FROM municipios WHERE nombre = 'Río Quito'), 'inundacion', '2025-06-15', 'medio', 'Revista Chocó', 'Desborde de los ríos Pato, Quito y Atrato afectó los corregimientos de San Isidro y La Soledad, en el municipio de Río Quito, con impacto sobre 300 familias (650 personas). Fuente: https://www.revistachoco.com.co/regional/22-municipios-del-choco-afectados-por-inundaciones/2025/');
