-- Eventos históricos reales del lote Pacífico/Darién (fuentes: prensa nacional
-- y regional, UNGRD). Verificación estricta de afectación directa por
-- municipio — se descartó un evento de marzo 2024 sobre "río Baudó" que en
-- realidad correspondía a Alto Baudó, no a Bajo/Medio Baudó. Sin eventos de
-- sequía documentados en estos 8 municipios (zona Pacífica/Darién extremadamente
-- húmeda) — reportado honestamente, no inventado.
INSERT INTO eventos_historicos (municipio_id, tipo_evento, fecha, severidad, fuente, descripcion) VALUES
((SELECT id FROM municipios WHERE nombre = 'Bajo Baudó'), 'inundacion', '2021-05-30', 'medio', 'El Tiempo', 'Erosión costera avanzada agravó el riesgo de inundación en Pizarro; el mar redujo franjas de tierra de 400 a 20 metros, afectando a 54 familias (242 personas) de Guachal y Ordó. Fuente: https://www.eltiempo.com/colombia/otras-ciudades/erosion-costera-e-inundaciones-amenazan-el-bajo-baudo-chocoano-592300'),
((SELECT id FROM municipios WHERE nombre = 'Bajo Baudó'), 'inundacion', '2026-08-16', 'alto', 'LaFM / El Tiempo', 'Tras el terremoto 7,4 del 10-ago-2026 y un vendaval el 11-ago, lluvias torrenciales dejaron la cabecera de Pizarro bajo el agua, acceso solo aéreo; parte de emergencia departamental de 29 municipios. Fuente: https://www.lafm.com.co/actualidad/inundaciones-sismo-y-vendaval-afectan-al-bajo-baudo-408515'),
((SELECT id FROM municipios WHERE nombre = 'Bajo Baudó'), 'deslizamiento', '2026-08-16', 'medio', 'LaFM', 'Deslizamiento en Guadualito (cuenca río Torreidó) afectó 4 viviendas, evacuación preventiva por inestabilidad del terreno. Fuente: https://www.lafm.com.co/actualidad/inundaciones-sismo-y-vendaval-afectan-al-bajo-baudo-408515'),
((SELECT id FROM municipios WHERE nombre = 'Medio Baudó'), 'inundacion', '2021-11-22', 'alto', 'El Espectador', 'Desbordamiento de ríos Baudó, Oro Chocó, Misará y Dubaza dejó 3.700+ familias damnificadas; 22 comunidades bajo el agua en Puerto Meluk. Fuente: https://www.elespectador.com/colombia/mas-regiones/fuertes-lluvias-dejan-mas-de-3700-familias-damnificadas-en-medio-baudo-choco/'),
((SELECT id FROM municipios WHERE nombre = 'Medio Baudó'), 'inundacion', '2026-08-16', 'alto', 'El Tiempo', 'Desbordamiento de la cuenca del río Misará dejó pérdidas graves en 11 comunidades, dentro de la emergencia de 29 municipios del Chocó. Fuente: https://www.eltiempo.com/colombia/otras-ciudades/de-la-destruccion-a-la-inundacion-el-choco-no-tiene-tregua-tras-el-devastador-terremoto-y-las-fuertes-lluvias-3578931'),
((SELECT id FROM municipios WHERE nombre = 'Bahía Solano'), 'inundacion', '2017-06-07', 'alto', 'UNGRD / El País', 'Desbordamiento de quebrada Chocolatal (avalancha) y río Jella inundó toda la cabecera de Bahía Solano, ~3.000 personas afectadas, 300 familias evacuadas. Fuente: https://www.elpais.com.co/colombia/empalizada-en-choco-deja-3-000-personas-afectadas-en-bahia-solano.html'),
((SELECT id FROM municipios WHERE nombre = 'Bahía Solano'), 'deslizamiento', '2017-06-07', 'medio', 'El País', 'Misma emergencia del 7-jun-2017: derrumbes sepultaron varias viviendas y derribaron dos puentes en el casco urbano. Fuente: https://www.elpais.com.co/colombia/empalizada-en-choco-deja-3-000-personas-afectadas-en-bahia-solano.html'),
((SELECT id FROM municipios WHERE nombre = 'Nuquí'), 'inundacion', '2024-06-05', 'medio', 'UNGRD', 'Desbordamiento de ríos Ostional y Aguas Calientes inundó Termales (Nuquí): 500 habitantes, 130 viviendas afectadas. Fuente: https://portal.gestiondelriesgo.gov.co/Paginas/Noticias/2024/UNGRD-atiende-emergencia-por-inundacion-en-el-corregimiento-de-Termales-en-Nuqui,-Choco.aspx'),
((SELECT id FROM municipios WHERE nombre = 'Juradó'), 'inundacion', '2024-06-15', 'alto', 'El Tiempo / El País', 'Ríos Juradó, Jampabadó y Apartadó en niveles históricos: 5.000+ damnificados en 14 comunidades, 3.000+ en la cabecera. Fuente: https://www.elpais.com.co/colombia/fuertes-lluvias-causan-emergencia-en-jurado-choco-el-municipio-se-encuentra-bajo-el-agua-1516.html'),
((SELECT id FROM municipios WHERE nombre = 'Acandí'), 'inundacion', '2021-05-23', 'alto', 'BluRadio', 'Desbordamiento de al menos 5 ríos afectó la cabecera de Acandí; 700+ familias asistidas, calamidad pública declarada. Fuente: https://www.bluradio.com/blu360/antioquia/graves-emergencias-en-unguia-y-acandi-choco-tras-crecientes-de-al-menos-cinco-rios'),
((SELECT id FROM municipios WHERE nombre = 'Unguía'), 'inundacion', '2019-12-30', 'critico', 'Noticias RCN', 'Desbordamiento del río Unguía inundó ~90% del casco urbano, ~1.200 familias afectadas. Fuente: https://www.noticiasrcn.com/colombia/emergencia-en-unguia-choco-por-inundaciones-350971'),
((SELECT id FROM municipios WHERE nombre = 'Unguía'), 'inundacion', '2021-04-08', 'alto', 'Radio Nacional de Colombia', 'Desbordamiento del río Tanela dejó 800 familias damnificadas en 10 comunidades, 43+ ha de cultivos destruidas. Fuente: https://www.radionacional.co/actualidad/desbordamiento-del-rio-tanela-deja-damnificadas-800-familias-en-unguia-choco'),
((SELECT id FROM municipios WHERE nombre = 'Carmen del Darién'), 'inundacion', '2021-01-11', 'alto', 'Infobae', 'Desbordamiento del río Atrato dejó 5.000 familias afectadas y 1.400 damnificados en Curbaradó y corregimientos. Fuente: https://www.infobae.com/america/colombia/2021/01/11/desbordamiento-del-rio-atrato-en-choco-deja-mas-de-5000-familias-afectadas-y-1400-damnificados/'),
((SELECT id FROM municipios WHERE nombre = 'Carmen del Darién'), 'inundacion', '2022-08-09', 'critico', 'Radio Nacional de Colombia', 'Río Atrato entró y salió de la cabecera ~5 meses continuos en 2022; 12.000+ personas afectadas. Fuente: https://www.radionacional.co/noticias-colombia/rio-atrato-12-mil-personas-afectadas-por-desbordamientos');
